-- MySQL Script generated by MySQL Workbench
-- Sun Oct 29 21:58:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `login` VARCHAR(6) NOT NULL,
  `senha` VARCHAR(8) NOT NULL,
  `primeiro_nome` VARCHAR(40) NOT NULL,
  `segundo_nome` VARCHAR(40) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `nome_materno` VARCHAR(40) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone_celular` VARCHAR(16) NOT NULL,
  `telefone_fixo` VARCHAR(16) NOT NULL,
  `tipo_logradouro` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` INT NULL DEFAULT NULL,
  `bairrro` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `tipo_user` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log` (
  `idlog` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `pergunta` VARCHAR(80) NOT NULL,
  `resposta` VARCHAR(80) NOT NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`idlog`),
  INDEX `fk_log_usuario_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_log_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
